development:
  adapter: postgresql
  encoding: utf8
  database: /home/robert/projects/cards/db/project_production
  host: localhost
  pool: 5
  username: postgres
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: /home/robert/projects/cards/db/project_production
  host: localhost
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: /home/robert/projects/cards/db/project_production
  host: localhost
  pool: 5
  username: postgres
  password: password
